modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="mob_loot_bags"
version="1.10.1"
displayName="Mob Loot Bags"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits yet"
authors="NAIZO"
description="With each mob you defeat, you have a chance to receive a loot bag containing valuable rewards"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mob_loot_bags]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.mob_loot_bags]]
modId="jauml"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mob_loot_bags]]
modId="jauml"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
