modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mob_loot_bags"
version="1.8.0"
displayName="Mob Loot Bags"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits yet"
authors="NAIZO"
description="With each mob you defeat, you have a chance to receive a loot bag containing valuable rewards"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mob_loot_bags]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mob_loot_bags]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration