["Loot Tables Rarity Config"]
	common_lt_name = "minecraft:chests/village/village_taiga_house"
	uncommon_lt_name = "minecraft:chests/village/village_snowy_house"
	rare_lt_name = "minecraft:chests/desert_pyramid"
	epic_lt_name = "minecraft:chests/shipwreck_treasure"
	legendary_lt_name = "minecraft:chests/end_city_treasure"

["Loot Bags Drop Rate Config"]
	common_drop_rate = 60.0
	uncommon_drop_rate = 20.0
	rare_drop_rate = 15.0
	epic_drop_rate = 4.0
	legendary_drop_rate = 1.0
	drop_chance_overall = 80.0
