
["Loot Tables Rarity Config"]
	epic_lt_name = ["mob_loot_bags:lootbags/epic"]
	custom_lt_name = "minecraft:chests/end_city_treasure"
	common_lt_name = ["mob_loot_bags:lootbags/common"]
	legendary_lt_name = ["minecraft:chests/end_city_treasure"]
	uncommon_lt_name = ["mob_loot_bags:un_common"]
	rare_lt_name = ["mob_loot_bags:lootbags/rare"]

["Loot Bags Drop Rate Config"]
	epic_drop_rate = 4.0
	legendary_drop_rate = 1.0
	rare_drop_rate = 15.0
	common_drop_rate = 60.0
	drop_chance_overall = 80.0
	uncommon_drop_rate = 20.0

